travis:
  secure:
    BINSTAR_TOKEN: Xop4QbEXgxqE+p7Xe1gqQXh0/m1/y+CkpczXXtdIdwIaNR0mBtV4WEIFWQZvyRMx5ea0xnCtg0uwWBUKhU2qcCHKvNtr+SaobKviELNGTQYLj6Qjp6HY5QWUWhF83Fh8bq9IQmaSHLluFswVqxmLws4tPxFoa4i8dITNFinH7dbt2jp3zAbBjRf7Sas6GhxIkfQuc3OZGPuUwDhLIAu8NOZLVE2EGXEmWD3wGzwR3OTSu3RWNah2Cj2mzLGKX8V8tYSzaFdqYwn7OS5V9LHIuhXM0GVGOv3C5P6l+Ynh+yeBFyOj5CUw2Q+nhmz6bevROU7iiAu75hazaOjc82VETUUr+7krQF5Y3+tKGh+23BL00VjcwW9qE3z5dugwXs0JzIfTergdIHZIxe+XfSy5OlKI23SBCOb6RQpqXy4RwdMDzBR90Pl9fxhIUD193iUj/PgGON5KQKfJOaUijzurTq/IBaqgwHIaZCokLYmfqi41ffikiEk1VttmtzdTLtfA1EpMLBF536FC+4WovGIZzqLDPFvbklEnlUOFIgGkBw6RlKFG9eWUQcielgI74dISECOHnIPQ3v4KVZW0HV3SbqAvIDHrpxA2v3GcxF1B37/yy/kDSZnlx2RUmDgnKhHVAZ5m/lQSxE8RxhJ3oaCvIxE5nU4TAKtM0JoUzJEWWH4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
